# Please note that this file was mostly generated by Qwen3.6-Plus

def main [
    labs: string
    file: string = "./res/sub_by_common_lab.json"
    --force (-f)
] {
    let result = (open $file |
        where lab_pattern == $labs |
        each { |row|
            let lab_list = ($row.lab_pattern | split row ",")
            let sub_list = ($row.subjects)

            $lab_list | each { |lab|
                $sub_list | each { |sub|
                  { "lab-sub": $"sub-($lab)($sub)" }
                }
            } | flatten
        } | flatten
    )

    let safe_labs = ($labs | str replace "," "_" --all)
    let filename = $"./res/sub_by_labs_($safe_labs)_filenames.csv"

    $result | to csv --noheaders | save $filename --force=$force
}
