# Please note that this file was mostly generated by Qwen3.6-Plus

def main [
    file: string = "./data/ls_output.txt"
    --force (-f)
] {
    open $file |
        split words |
        parse --regex '(?<lab>[A-Za-z]+)(?<sub>\d+)' |
        group-by sub |
        items { |key, value|
            {
                subject: $key,
                labs: ($value | get lab | uniq | sort | str join ",")
            }
        } |
        group-by labs |
        items { |key, value|
            {
                lab_pattern: $key,
                subjects: ($value | get subject | sort),
                count: ($value | get subject | length)
            }
        } |
        where count > 1 |
        sort-by count -r |
        to json |
        save ./res/sub_by_common_lab.json --force=$force
}
