#!/usr/bin/env bash
# Please note that this file was generated by Qwen3.6-Plus and fine tuned by myself

set -euo pipefail

# Initialize all variables to empty
RUN_NUM=""
SUBJECTS_STR=""
DATA_DIR=""
N_SUBS_IN_PARALLEL=""
OUT_DIR=""
WORK_DIR=""
LICENSE_FILE=""

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --run-num)
      [[ -z "${2:-}" ]] && { echo "Error: --run-num requires a value"; exit 1; }
      RUN_NUM="$2"; shift 2 ;;
    --subjects)
      [[ -z "${2:-}" ]] && { echo "Error: --subjects requires a value"; exit 1; }
      SUBJECTS_STR="$2"; shift 2 ;;
    --data-dir)
      [[ -z "${2:-}" ]] && { echo "Error: --data-dir requires a value"; exit 1; }
      DATA_DIR="$2"; shift 2 ;;
    --n-subs-in-parallel)
      [[ -z "${2:-}" ]] && { echo "Error: --n-subs-in-parallel requires a value"; exit 1; }
      N_SUBS_IN_PARALLEL="$2"; shift 2 ;;
    --out-dir)
      [[ -z "${2:-}" ]] && { echo "Error: --out-dir requires a value"; exit 1; }
      OUT_DIR="$2"; shift 2 ;;
    --work-dir)
      [[ -z "${2:-}" ]] && { echo "Error: --work-dir requires a value"; exit 1; }
      WORK_DIR="$2"; shift 2 ;;
    --license-file)
      [[ -z "${2:-}" ]] && { echo "Error: --license-file requires a value"; exit 1; }
      LICENSE_FILE="$2"; shift 2 ;;
    *)
      echo "Unknown option: $1"
      exit 1 ;;
  esac
done

# Validate all required arguments are provided
if [[ -z "$RUN_NUM" || -z "$SUBJECTS_STR" || -z "$DATA_DIR" || -z "$N_SUBS_IN_PARALLEL" || -z "$OUT_DIR" || -z "$WORK_DIR" || -z "$LICENSE_FILE" ]]; then
  cat <<EOF
Error: All arguments are required. No defaults are set.

Usage:
  $0 --run-num <num> \
     --subjects <sub1,sub2,...> \
     --data-dir <path> \
     --n-subs-in-parallel <int> \
     --out-dir <path> \
     --work-dir <path> \
     --license-file <path>

Arguments:
  --run-num                 Run identifier (e.g., 1)
  --subjects                Comma-separated subject IDs (e.g., "001,060,120")
  --data-dir                Path to BIDS data directory
  --n-subs-in-parallel       Number of parallel sub Docker jobs to run
  --out-dir                 Path to output directory
  --work-dir                Path to work/scratch directory
  --license-file            Path to FreeSurfer license file
EOF
  exit 1
fi

# Validate N_SUBS_IN_PARALLEL is a positive integer
if ! [[ "$N_SUBS_IN_PARALLEL" =~ ^[0-9]+$ ]] || [[ "$N_SUBS_IN_PARALLEL" -eq 0 ]]; then
  echo "Error: --n-subs-in-parallel must be a positive integer greater than 0."
  exit 1
fi

# Validate license file exists
if [[ ! -f "$LICENSE_FILE" ]]; then
  echo "Error: License file not found at $LICENSE_FILE"
  exit 1
fi

# Convert comma-separated subjects to bash array
IFS=',' read -r -a SUBJECTS <<< "$SUBJECTS_STR"
if [[ ${#SUBJECTS[@]} -eq 0 ]]; then
  echo "Error: No subjects provided."
  exit 1
fi

echo "Running fmriprep for ${#SUBJECTS[@]} subjects (${N_SUBS_IN_PARALLEL} at a time)..."
echo "Subjects: ${SUBJECTS[*]}"


# Pre-create work directories to ensure correct permissions before Docker mounts them
for sub in "${SUBJECTS[@]}"; do
  TARGET_DIR="${WORK_DIR}/run-${RUN_NUM}-${sub}"
  echo "Creating: $TARGET_DIR"
  mkdir -p "$TARGET_DIR" || { echo "ERROR: Failed to create $TARGET_DIR"; exit 1; }
done

# Pre-create output directory
mkdir -p "${OUT_DIR}/run-${RUN_NUM}"

DOCKER_IMAGE="madeinshinea/fuzzy-fmriprep:25.2.5"

if ! docker inspect "$DOCKER_IMAGE" &>/dev/null; then
  echo "Image '$DOCKER_IMAGE' not found locally. Pulling..."
  docker pull "$DOCKER_IMAGE" || { echo "❌ ERROR: Failed to pull image. Exiting."; exit 1; }
  echo "Successfully pulled $DOCKER_IMAGE"
else
  echo "Image '$DOCKER_IMAGE' already exists locally."
fi
# --- End Image Check -

# Execute in parallel
printf '%s\n' "${SUBJECTS[@]}" | parallel -j "${N_SUBS_IN_PARALLEL}" --joblog "/home/cbi/olivier.amacker/bachelor-thesis/bachelor-thesis-project/parallel_fmriprep_run_${RUN_NUM}.log" \
    docker run --rm \
    -u "$(id -u):$(id -g)" \
    -v "${DATA_DIR}:/data:ro" \
    -v "${OUT_DIR}/run-${RUN_NUM}:/out" \
    -v "${WORK_DIR}/run-${RUN_NUM}-{}/:/work" \
    -v "${LICENSE_FILE}:/opt/freesurfer/license.txt:ro" \
    madeinshinea/fuzzy-fmriprep:25.2.5 /data/ /out participant \
    --skull-strip-fixed-seed \
    --omp-nthreads 1 \
    --random-seed 42 \
    --participant-label {} \
    --skip-bids-validation \
    --md-only-boilerplate \
    --cifti-output 91k
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --stop-on-first-crash \
    -w /work

echo "All subjects submitted. Check 'parallel_fmriprep_run_${RUN_NUM}.log' for details."
