#!/usr/bin/env bash
# Please note that this file was generated by Qwen3.6-Plus and fine tuned by myself

set -euo pipefail

if [ $# -lt 1 ]; then
  echo "Usage: $0 <run_number>"
  echo "Example: $0 1"
  exit 1
fi

# Configuration
RUN_NUM="$1"
N_JOBS=3
DATA_DIR="./data/reproduction-data"
OUT_DIR="./output"
WORK_DIR="./work"
LICENSE_FILE="./license.txt"

# SUBJECTS=("001" "030" "060" "090" "120")
SUBJECTS=("001" "060" "120")


# Check if the array is empty
if [ ${#SUBJECTS[@]} -eq 0 ]; then
  echo "No subjects defined in the SUBJECTS array."
  exit 1
fi

echo "Running fmriprep for ${#SUBJECTS[@]} subjects (${N_JOBS} at a time)..."
echo "Subjects: ${SUBJECTS[*]}"

# Pre-create work directories to ensure correct permissions before Docker mounts them
for sub in "${SUBJECTS[@]}"; do
  mkdir -p "$(pwd)/${WORK_DIR}/run-${RUN_NUM}-sub-${sub}"
done
# Pre-create output directory
mkdir -p "$(pwd)/${OUT_DIR}/reproduction/run-${RUN_NUM}"

# Pass the array to parallel using printf

printf '%s\n' "${SUBJECTS[@]}" | parallel -j "${N_JOBS}" --joblog parallel_fmriprep_run_${RUN_NUM}.log \
    docker run --rm \
    -u $(id -u):$(id -g) \
    -v "$(pwd)/${DATA_DIR}:/data:ro" \
    -v "$(pwd)/${OUT_DIR}/reproduction/run-${RUN_NUM}:/out" \
    -v "$(pwd)/${WORK_DIR}/run-${RUN_NUM}-sub-{}/:/work" \
    -v "$(pwd)/${LICENSE_FILE}:/opt/freesurfer/license.txt:ro" \
    madeinshinea/fuzzy-fmriprep:25.2.5 /data /out participant \
    --skull-strip-fixed-seed \
    --participant-label {} \
    --skip-bids-validation \
    --md-only-boilerplate \
    --fs-no-reconall \
    --output-spaces MNI152NLin2009cAsym:res-2 \
    --stop-on-first-crash \
    -w /work

echo "All subjects submitted. Check 'parallel_fmriprep_run_${RUN_NUM}.log' for details."
