# Please note that this file was generated by Qwen3.6-Plus


#!/usr/bin/env bash
set -euo pipefail

# Configuration
N_JOBS=1
DATA_DIR="./data/reproduction-data"
OUT_DIR="./output"
WORK_DIR="./work"
LICENSE_FILE="./license.txt"

# Extract subject IDs (e.g., 01, 02, 08...)
SUBJECTS=$(ls -1d "${DATA_DIR}"/sub-* 2>/dev/null | sed 's|.*/sub-||')

if [ -z "$SUBJECTS" ]; then
  echo "No 'sub-*' directories found in ${DATA_DIR}"
  exit 1
fi

echo "Running fmriprep for $(echo "$SUBJECTS" | wc -w) subjects (${N_JOBS} at a time)..."

echo "$SUBJECTS" | parallel -j "${N_JOBS}" --joblog parallel_fmriprep.log docker run --rm \
  -v "$(pwd)/${DATA_DIR}:/data:ro" \
  -v "$(pwd)/${OUT_DIR}:/out" \
  -v "$(pwd)/${WORK_DIR}-{}:/work-{}" \
  -v "$(pwd)/${LICENSE_FILE}:/opt/freesurfer/license.txt:ro" \
  fuzzy-fmriprep /data /out participant \
  --skull-strip-fixed-seed \
  --participant-label {} \
  --skip-bids-validation \
  --md-only-boilerplate \
  --fs-no-reconall \
  --output-spaces MNI152NLin2009cAsym:res-2 \
  --stop-on-first-crash \
  -w /work-{}

echo "All subjects submitted. Check 'parallel_fmriprep.log' for details."
